# Generated by Django 5.0.2 on 2024-03-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='data_criacao',
            field=models.DateTimeField(),
        ),
    ]
