# Generated by Django 5.0.2 on 2024-03-04 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_imagem_data_criacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='imagem',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_analise', models.DateTimeField(auto_now_add=True)),
                ('comentarios', models.TextField()),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('imagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.imagem')),
                ('doenca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.doenca')),
            ],
        ),
    ]
