# Generated by Django 5.0.2 on 2024-03-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_doenca_alter_imagem_data_criacao_analise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doenca',
            name='nome',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='classe',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
