# Generated by Django 5.0.2 on 2024-03-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_doenca_nome_alter_imagem_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='classe',
            field=models.BooleanField(default=False),
        ),
    ]
