# Generated by Django 5.0.2 on 2024-03-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_imagem_classe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analise',
            name='comentarios',
        ),
        migrations.AlterField(
            model_name='doenca',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
