# Generated by Django 5.0.2 on 2024-03-06 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_remove_analise_comentarios_alter_doenca_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doenca',
            name='descricao',
        ),
    ]
